<template>
	<div class="ib-app">
		<carousel
			v-if="thumbnailData.length > 2"
			:images="thumbnailData"
			@carousel-load="onCarouselLoad"
			@carousel-item-click="onItemClick"
		>
		</carousel>

		<teleport :to="teleportTarget">
			<overlay
				v-if="activeImage"
				:images="thumbnailData"
				:active-image="activeImage"
				@close-overlay="onCloseOverlay"
				@vtoc-item-click="onItemClick"
				@vtoc-view-in-article="onViewInArticle"
			></overlay>
		</teleport>
	</div>
</template>

<script>
const { defineComponent, ref, inject } = require( 'vue' );
const router = require( 'mediawiki.router' );
const { extractThumbInfo } = require( './thumbExtractor.js' );
const Carousel = require( './components/Carousel.vue' );
const Overlay = require( './components/Overlay.vue' );

// @vue/component
module.exports = exports = defineComponent( {
	name: 'ImageBrowsing',
	components: {
		Carousel,
		Overlay
	},
	setup() {
		const submitInteraction = inject( 'submitInteraction' );

		const thumbnailData = ref( [] );
		const activeImage = ref( null );
		const clickCounter = ref( 0 );

		// Extract thumbnail image (as an array of ImageData objects)
		// from the content of the underlying article page.
		const content = document.getElementById( 'content' );
		if ( content ) {
			// Grab all image info, removing those that failed to parse
			thumbnailData.value = extractThumbInfo( content ).filter( ( img ) => img.name );
		}

		const teleportTarget = inject( 'CdxTeleportTarget' );

		// Client-side routing config
		// Set up route for overlay images
		const routePrefix = '/imagebrowsing/';
		// Add a dynamic route that matches `/imagebrowsing/*` to support per-image navigation
		router.addRoute(
			// eslint-disable-next-line security/detect-non-literal-regexp
			new RegExp( '^' + RegExp.escape( routePrefix ) + '(.+)$' ),
			( prefixedDbFileTitle ) => {
				const uriDecoded = decodeURIComponent( prefixedDbFileTitle );
				const image = thumbnailData.value.find(
					( imageData ) => imageData.title.getPrefixedDb() === uriDecoded
				);
				if ( image ) {
					activeImage.value = image;
				} else {
					// Invalid images should not be a hard fail, since it is possible that
					// a completely valid url got shared, but the image has since been removed
					// from the page
					// eslint-disable-next-line no-console
					console.error( '[ImageBrowsing] Invalid navigation image; could not find:', name );
					activeImage.value = null;
				}
			},
			() => {
				// This teardown handler is called when transitioning from a matching route
				// (i.e. one with /imagebrowsing/ + filename, where we want to show the image)
				// to one that doesn't (anything else - like going back to no hash (closing the
				// image, or through browser history)) where we don't want an image
				activeImage.value = null;
			}
		);
		// Check the current route & immediately navigate to the relevant imagine
		// in case the user came from a shared/history URL
		router.checkRoute();
		// Helper function to simplify navigation to images, just so that those event
		// handlers don't have to worry about constructing the appropriate route path
		function navigateTo( image ) {
			let path;

			if ( !image ) {
				// explicit navigation out of this app
				path = '';
			} else if ( image.title ) {
				// navigate to image
				path = routePrefix + image.title.getPrefixedDb();
			} else {
				// Invalid input to this function would be generated by code & should fail hard
				// eslint-disable-next-line no-console
				console.error( '[ImageBrowsing] Invalid navigation input; expected ImageData but received:', image );
				throw new Error( '[ImageBrowsing] Invalid navigation input' );
			}

			router.navigate( path );
		}

		// Instrument carousel load
		function onCarouselLoad() {
			// eslint-disable-next-line camelcase
			submitInteraction( 'image_carousel_load', { action_source: 'init' } );
		}

		/**
		 * When a carousel item is clicked by the user, set that image as
		 * the active image and show the overlay part of the UI.
		 *
		 * @param {import('./types').ImageData} image
		 */
		function onItemClick( image ) {
			clickCounter.value += 1;

			// Instrument click on a carousel image
			/* eslint-disable camelcase */
			const interactionData = {
				action_subtype: 'view_image',
				action_source: 'image_carousel'
			};
			if ( clickCounter.value === 1 ) {
				interactionData.action_context = 'image1';
			}
			/* eslint-enable camelcase */
			submitInteraction( 'click', interactionData );

			navigateTo( image );
		}

		/**
		 * @param {import('./types').ImageData} image
		 */
		function onViewInArticle( image ) {
			onCloseOverlay();

			// Scroll the main page view to the image in context.
			// Do not use image.thumb, as that may be a lazy-load placeholder
			// span which has already been replaced; use the container.
			if ( image.container ) {
				// In mobile mode, sections may be collapsed.
				// Toggle the section if necessary.
				const section = image.container.closest( '.collapsible-block-js' );
				if ( section && section.classList && !section.classList.contains( 'open-block' ) ) {
					const headingWrapper = section.previousSibling;
					if ( headingWrapper ) {
						headingWrapper.click();
					}
				}
				image.container.scrollIntoView( {
					behavior: 'smooth'
				} );
			}
		}

		/**
		 * When a "close" event has been emitted from the Overlay component,
		 * clear the active image and hide the overlay part of the UI.
		 */
		function onCloseOverlay() {
			// Instrument overlay close
			// eslint-disable-next-line camelcase
			submitInteraction( 'image_carousel_load', { action_source: 'close' } );

			navigateTo( null );
		}

		return {
			thumbnailData,
			onCarouselLoad,
			onItemClick,
			onViewInArticle,
			onCloseOverlay,
			activeImage,
			teleportTarget
		};
	}
} );
</script>

<style lang="less">
// @hack why is this necessary to get the overlay to show up properly? Fix and remove
#mw-teleport-target {
	top: 0;
	left: 0;
}
</style>
